server:
  port: 9003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost3
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true