server:
  port: 9002
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost2
  client:
    serviceUrl:
      defaultZone: http://localhost:9003/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true